// STO USANDO INVERSIFY JS PER CREARE DEI CONTAINER CON CUI FARE DEPENDENCY INJECTION E RENDERE LE CLASSI DEI SINGLETON, IN MODO DA NON DOVER IMPLEMENTARE DEGLI OGGETTI CONCRETI NEL CONTROLLER, MA AVERE UN CONTAINER CHE RICONOSCE UNO SPECIFICO TIPO E INSTANZIA DA SOLO LA CLASSE E LA DISTRUFGGE QUANDO NON SERVE PIù --- MIGLIORAMENTO DELLE PERFORMANCE DELL APPLICAZIONE

// TIPI PER LO USER
export const TYPES = {
    USER_REPOSITORY: Symbol.for("UserRepository"),
    USER_CONTROLLER: Symbol.for("UserController"),
    USER_SERVICES: Symbol.for("UserServices"),
};

// export default { TYPES };
